### ISSUE TITLE
dynamic link library relocation issue

### ISSUE THREAD

**Issue by Zero-Fanker** [CnCNet/cncnet-for-ares#1]
![image](https://user-images.githubusercontent.com/14891010/98267209-1585ad80-1fc6-11eb-99c2-c8b2800509af.png)
This is the screenshot of what syringe logs out . I modified syringe a bit so i can have more details come out .
As i  am only encountered with such issue once, but once for all retrials until i restart my operating system, i found it quite serious in my perspective . 

As far as i know, cncnet5.dll uses a **STATIC** address and assumes it never changes when calculating and apply the patch hooks, so once such address is somehow taken by another module, all its patching will fail, and the game can never start again until the wanted address is freed.
I have been working on expansion of YR Ares for years, and i am familiar with the syringe logic, which can prevent such problems, while cncnet5 is using opcode E8 with relative address based on the **STATIC** address just mentioned .
I hope such problem can be solved by any kind of method, i can also offer my help if needed, thanks !

**Comment by Belonit** [comment]
The problem is not with the static address. Starting from windows vista all dlls are forced to be dynamic. The problem is that cncnet5.dll interferes with Syringe.exe memory is the same. DllMain (which applies the patch) Called for both EXE modules. In PR #2, I propose a workaround, register one hook into which to transfer all the logic of the patch.
This way the patch will work only for gamemd.exe

**Comment by Zero-Fanker** [comment]
> The problem is not with the static address. Starting from windows vista all dlls are forced to be dynamic. The problem is that cncnet5.dll interferes with Syringe.exe memory is the same. DllMain (which applies the patch) Called for both EXE modules. In PR #2, I propose a workaround, register one hook into which to transfer all the logic of the patch.
> This way the patch will work only for gamemd.exe

I don't think your method is adequate to solve this problem, according to cncnet-yr patching logic as you can referenced [here]( 
https://github.com/CnCNet/ts-patches/blob/2f2509415de98bbc640224bbd64afeb5be34b1a1/inc/macros/patch.inc#L138)

```ASM
%macro @CALL 2
    @PATCH (%1)
    db 0xE8                     ; far call
    dd (%2) - (%1) - 5          ; relative offset
    @ENDPATCH
%endmacro
```

the 'dd (%2) - (%1) - 5          ; relative offset' calculation restricts the hook address to the patched address distance . e.g. hook at 0x6BC0DC of gamemd.exe, and jump to 0x6BBC14B0 in cncnet5.dll, 0x6B5053CF =  0x6BBC14B0 - 0x6BC0DC - 5, which will work if cncnet5.dll can have expected address in process at 0x6BBC0000, but what if 0x6BBC0000 is taken by other dynamic libraries unexpectedly ? let's say  0x10BBC0000, then 0x6BBC14B0 will become 0x10BBC14B0, what is the result of  0x10BBC14B0 - 0x6BC0DC - 5 ? There should be a calculation fix to deal with such case .

```ASM
.patch:6BBC6000     ; Segment permissions: Read/Write
.patch:6BBC6000     _patch          segment dword public 'DATA' use32
.patch:6BBC6000                     assume cs:_patch
.patch:6BBC6000                     ;org 6BBC6000h
.patch:6BBC6000                     dd 6BC0DCh              ; address
.patch:6BBC6004                     dd 5
.patch:6BBC6008                     db 0E8h ;              ; call
.patch:6BBC6009                     dd 6B5053CFh
```

**Comment by Belonit** [comment]
@Zero-Fanker This problem is addressed at the system and compiler levels. Just take a look at this - [Relocation table](https://en.wikipedia.org/wiki/Relocation_(computing)). And the compiler works correctly in this case. It adds all these pointers to the `.reloc` section, which will allow the operating system to correctly count all of these pointers.
![image_2021-03-29_12-13-41](https://user-images.githubusercontent.com/54427022/112814864-65096a80-9088-11eb-94be-e2f33a55532a.png)

**Comment by Zero-Fanker** [comment]
> @Zero-Fanker This problem is addressed at the system and compiler levels. Just take a look at this - [Relocation table](https://en.wikipedia.org/wiki/Relocation_(computing)). And the compiler works correctly in this case. It adds all these pointers to the `.reloc` section, which will allow the operating system to correctly count all of these pointers.
> ![image_2021-03-29_12-13-41](https://user-images.githubusercontent.com/54427022/112814864-65096a80-9088-11eb-94be-e2f33a55532a.png)

You are right, i've rechecked and found the compiler do set address offset in ".patch" section into ".reloc" section, but i haven't checked whether it will work properly as expected .
